### PR TITLE
Add nested tabs and modals

### PR DESCRIPTION
**Pull request by DavZim**
Hi Kyle,
sorry for the next PR before the package even hit CRAN...
I found that these functions were missing and thought they would be useful in the package.

This PR adds nested tabs (ie another tabset within a first tabset) as well as modals to shiny.tailwind.

Each functionality is documented and has its own example (09-nested-tabs and 10-modal).

Let me know what you think about these! I am quite happy with the nested tabs; the modal is ok but could be more elegant in my view (but good-enough for now...)

### CODE REVIEW

**Comment by DavZim** [comment]
Moving the discussion around CRAN submission from #7 

Comments should be all addressed, the only exceptions is the backtick in the documentation which is ok following roxygen2 (markdown=TRUE).

If you are ok with the additions of modal and nested tabs, feel free to merge and resubmit!

**Comment by kylebutts** [comment]
Crud, didn't mean to hit merge. I think one thing is that `document.getElementById('shiny-modal').classList.remove('hidden')` only allows for their to be one singular modal. I would probably make the id be based on the `btn_id`, e.g. "opan_modal". That way the id uniquely links a modal and a button

**Comment by kylebutts** [comment]
Also, there is some problem with the code. You're using `glue` like syntax which isn't going through I think
CleanShot 2022-09-07 at 16 12 34@2x
CleanShot 2022-09-07 at 16 12 19@2x

**Comment by DavZim** [comment]
Oh no, that happens when you create a PR late at night... Sorry for the incomplete/wrong code. #10 fixes the glue syntax issue.

Regarding the modal functionality. I see what you mean, however, afaik [shiny's modals](https://shiny.rstudio.com/reference/shiny/latest/modalDialog.html) behave in the same way in that you can only have one modal open at the same time. We could change this to have a modal-id similar to tabsetid in the nested tabs functionality.

**Pull request merged**
