### PR TITLE
Add support for the Just in Time compiler CDN

### PR DESCRIPTION
**Pull request by yogat3ch**
Adds an argument `use_jit` to `use_tailwind` to use the JIT Compiler

### CODE REVIEW

**Comment by kylebutts** [comment]
Before merging, I think Beyond Code's version is deprecated. It was created before Tailwind had a JIT mode themselves. That means it won't support all the new Tailwind features that come. Is there any features that Beyond Code offers that Tailwind's version doesn't?

**Comment by yogat3ch** [comment]
@kylebutts Im honestly not sure. If it's out of date and isn't really that useful feel free to close

**Comment by kylebutts** [comment]
Thanks for your help on all the PRs! Maintenance is essential :-)

**Comment by yogat3ch** [comment]
> Thanks for your help on all the PRs! Maintenance is essential :-)

No problem thanks for the quick turnaround on review!

**Pull request closed without merging**
